T6307: Add dependency procps to build vyos-1x
This fixes the sysctl dependency
```
======================================================================
ERROR: test_sysctl_read (test_utils.TestVyOSUtils.test_sysctl_read)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vyos/work/tmp/vyos-1x/src/tests/test_utils.py", line 28, in test_sysctl_read
    self.assertEqual(sysctl_read('net.ipv4.conf.lo.forwarding'), '1')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/vyos/work/tmp/vyos-1x/python/vyos/utils/system.py", line 28, in sysctl_read
    tmp = run(['sysctl', '-nb', name], capture_output=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sysctl'
```

(cherry picked from commit 9d07adceb77fe611d82b0242e28f1ca7c4637ef3)