Revert "Kernel: T2955: Update Linux Kernel to v4.19.149"
This reverts commit b481a3ee4c947d78cb1488b542c31c23cd473b7f.

Perf utils do not build anymore:

util/evsel.c: In function ‘perf_evsel__exit’:
util/util.h:25:28: error: passing argument 1 of ‘free’ discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
 #define zfree(ptr) ({ free(*ptr); *ptr = NULL; })
util/evsel.c:1293:2: note: in expansion of macro ‘zfree’
  zfree(&evsel->pmu_name);
  ^~~~~
/usr/include/stdlib.h:563:25: note: expected ‘void *’ but argument is of type ‘const char *’
 extern void free (void *__ptr) __THROW;
                   ~~~~~~^~~~~
  ASCIIDOC perf-probe.xml