jool: T5499: fix AttributeError: 'int' object has no attribute 'strip'
This fixes an error introduced by commit 3d5445d8f7c0 ("T5499: arm64: build
jool with correct depends").